name: Continuous Integration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main, master]
    paths-ignore:
      - 'tests/**'
  pull_request:
    branches: [main, master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  TestTemplate:

    runs-on: ubuntu-latest

    steps:
      - name: Install Template Runner
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --force git+https://github.com/tercen/workflow_runner
      - name: Test template 
        id: run_test
        run: |
          python3 -m workflow_runner.template_tester \
          --templateRepo=tercen/simple_workflow_template_test \
          --gsRepo=tercen/simple_workflow_template_test \
          --gsPath=tests/Simple_gs.zip \
          --user=${{ secrets.TERCEN_TEST_OPERATOR_USERNAME }} \
          --passw=${{ secrets.TERCEN_TEST_OPERATOR_PASSWORD }} \
          --serviceUri=${{ secrets.TERCEN_TEST_OPERATOR_URI }} \
          --filename="Crabs Data.csv"
      # - name: Check Success
      #   run: |
      #     if [ ${{steps.run_test.test_result}} == '[[]]' ]; then 
      #       echo "Test passed" 
      #     fi 
        

